src/examples.md

The description for example 12 included some copy paste error i guess.

Correct example 12 description

---

src/examples.md
src/features.md

Improved documentation for example 18.

Improve hydrodynamics documentation [hydro-doc-dev]

---

src/publications.md

I have added my publications. We were having issues installing the latest version of mkdocs and so could not run mkdocs serve. Please let me know if there are any problems.

adding publications

---

src/examples.md
src/features.md

This PR adds some documentation into features and examples as needed. 
Please feel free to let me know if anything is missing.
Closes #26 .
Related PR in main MFEM : https://github.com/mfem/mfem/pull/1127

Mention Ginkgo's features and examples.

---

src/examples.md
src/features.md

Short description about the ParaView features:
Another visualization format natively supported by MFEM is ParaView (www.paraview.org).  The file format supports high-order (up to order six) meshes and elements.

	modified:   features.md

---

src/index.md
src/news.md

Added MFEM video link

---

README.md

Added a note to README about specifying a port for Windows users in order to preview locally

Update README with port example

---

src/examples.md
src/features.md

As mentioned in https://github.com/mfem/web/issues/69.
I will create a PR on `mfem/mfem` regarding the Doxygen documentation. I made a link to the documentation but it does not seem to appear online yet.

Mention for SLEPc support and examples

---

src/examples.md
src/features.md

Addressing #78 - Minor updates to document latest additions to gslib-based miniapps.

Updating documentation for interpolation miniapps

---

src/fem.md
src/nonlininteg.md

This is a proposed enhancement for the website to mention nonlinear integrators. I'd like to see someone else contribute some words for Hyperelasticity because I'm not familiar with the physics there.
We can also use the opportunity to clarify the essential boundary "effect" on the local action of the `NonlinearForm`.

[WIP] Draft for adding documentation of nonlinear integrators

---

src/about.md

For https://github.com/mfem/web/pull/83
(I don't seem to have the permission to edit directly that PR)

Add contributor to mfem-4.2

---

src/index.md
src/news.md

Sorry @tzanio, just realized I forgot to create a new branch for this and am using an old one. However, my changes are very narrow and shouldn't affect the rest of the site. Added news items for S&TR and annual report; deleted job posting.

News updates for S&TR and annual report

---

src/about.md
src/howto/findpts.md

HowTo article on FindPointsGSLIB

---

src/howto/assembly_levels.md

This PR proposes an HowTo article for the assembly levels and the different backends in MFEM.
Resolve mfem/mfem#2313

Add an HowTo article about assembly levels

---

src/index.md
src/news.md
src/workshop.md

Add a page describing the upcoming community workshop.

MFEM Community Workshop

---

src/howto/install-with-spack.md

[WIP] First pass at writing a Spack intro for MFEM

---

README.md
src/bilininteg.md
src/building.md
src/code-overview.md
src/coefficient.md
src/fem.md
src/fem_bc.md
src/fem_weak_form.md
src/gpu-support.md
src/howto/assembly_levels.md
src/howto/build-systems.md
src/howto/custom_precond.md
src/howto/element-local-global-numbering.md
src/howto/findpts.md
src/howto/howto-index.md
src/howto/install-with-spack.md
src/howto/nav-mesh-connectivity.md
src/howto/ncmesh.md
src/howto/outer_normals.md
src/howto/periodic-boundaries.md
src/lininteg.md
src/lininterp.md
src/mesh-format-v1.0.md
src/mesh-format-v1.x.md
src/nonlininteg.md
src/parallel-tutorial.md
src/pri-dual-vec.md
src/serial-tutorial.md
template/toc.html

(Potentially) Resolves https://github.com/mfem/web/issues/134

Better navigational context

---

src/index.md
src/workshop.md

* Added simulation contest details.
* Changed contact email address.
We probably should update the tentative schedule posted on this page too.

MFEM Workshop Page Updates

---

src/index.md

Added Jupyter notebook link to main page

---

src/seminar.md
src/videos.md

Updated seminar page & videos page with YouTube links and abstracts for the most recent two seminar videos

Add Chiodi & Puso videos

---

src/tutorial/index.md
template/css/base.css

Adds a mermaid flowchart for the tutorial structure:

Add tutorial flowchart

---

src/index.md
src/news.md
src/workshop.md
src/workshop21.md

Draft page for the 2022 MFEM workshop

---

src/seminar.md
src/videos.md

Updated seminars & videos pages with the latest video

Add Vinuesa YouTube link

---

src/howto/custom_precond.md

This PR fixes a few small typos.

custom precond: typos

---

src/about.md
src/download.md
src/features.md
src/index.md
src/news.md

Website changes for mfem-4.5

---

src/howto/assembly_levels.md

Update Features table to mention Mixed elements support with libCEED.

Update "Mixed elements support".

---

src/index.md
src/news.md

Updated home page and news page

Add article link to news

---

src/videos.md
src/workshop.md

For the first 6 videos posted to YouTube:
- updated `videos.md` with new section heading, 6 videos with abstracts, & corrected 2021 workshop links
- updated `workshop.md` with video links

First batch of workshop videos

---

src/seminar.md
src/videos.md

- Updated Seminar page with YouTube link
- Updated Videos page with link and abstract

Add Lin Mu video info

---

src/seminar.md
src/videos.md

The usual updates to `seminar.md` and `videos.md`

Add Gavini & Schöberl videos

---

src/seminar.md
src/videos.md

The latest two seminar videos - added to the seminar and videos pages

Add two videos

---

src/gpu-support.md

This PR updates `src/gpu-support.md` with `mfem::forall`.
Resolves #217

Update src/gpu-support.md with mfem::forall

---

mkdocs.yml
src/index.md
src/news.md
src/tutorial/index.md
src/workshop.md
src/workshop22.md

Page for the 2023 MFEM community workshop

---

src/seminar.md
src/videos.md

Witherden & Sharma videos are posted to the YouTube playlist. I commented out much of the "Next Talk" until the title, abstract, time, and WebEx link are known. I don't have Dr. Sharma's PDF, which needs to be added (the button on `seminar.md` is currently unclickable).

Add two recent seminar videos

---

src/seminar.md
src/videos.md

Add Ben Southworth video link

---

src/index.md
src/news.md
src/workshop.md

- Added link to `workshop.md`
- Add link to home page and `news.md`
- Updated `news.md` links to past workshops

Add workshop article links

---

src/examples.md

This is the companion PR to mfem/mfem#3598.

New hyperbolic form integrators and updated Example 18

---

src/seminar.md
src/videos.md

Sungho Lee & Bill Moses YouTube links. Also un-abbreviated months on the seminars page for consistency.

Add two seminar videos

---

src/mesh-formats.md

Related to mfem/mfem#4239
cc: @samuelpmishLLNL

Add note about VTK/VTU attributes

---

src/about.md

Added Jan to contributors.

---

mkdocs.yml
src/index.md
src/news.md
src/workshop.md
src/workshop23.md

Initial draft for the 2024 MFEM community workshop page.

2024 Workshop page

---

src/mesh-format-v1.0.md

Following up on a question from @samuelpmishLLNL.

Fix space dimension comment in mesh format docs

---

src/fem_bc.md

Clarify DG BCs

---

src/tutorial/fem.md
src/tutorial/meshvis.md

Updating misc things such as references for the tutorial

Tutorial small fixes

---

src/tutorial/docker.md
src/tutorial/fem.md

I made a few tweaks to the "Finite Element Basics" portion of the tutorial and fixed a typo under the Docker instructions. Thanks for reviewing!

tutorial tweaks

---

src/seminar.md
src/tutorial/index.md
src/videos.md

- add Farrell seminar video
- add HPC tutorial video

Video catchup

---

src/workshop.md

Rephrased the sentence to match that on the 2023 workshop page

Add 2024 playlist link to workshop page

---

src/seminar.md
src/videos.md

Updated the seminar and videos page. This is a branch off `master` but should not conflict with https://github.com/mfem/web/pull/303.

Add Panozzo seminar video

---

src/seminar.md
src/videos.md

Updated videos page and seminar page

Add Tokareva seminar video

---

src/seminar.md

I removed double spaces on the `seminar.md` page to make sure I can contribute to this repo from my new laptop and its WSL setup.

Test to contribute from new laptop

---

src/seminar.md
src/videos.md

Updated the seminar and videos pages

Add Witherden seminar video

---

src/seminar.md
src/videos.md

The usual updates to seminar and videos pages.

Add Williams seminar video
