- src/mesh-format-v1.x.md
As pointed out in MFEM issue [#1519](https://github.com/mfem/mfem/issues/1519) the periodic example mesh does not run in the current version of example 1.  The cause is that the mesh file has node index 16 but specifies a total of 16 nodes.  Consequently, MFEM expects the nodes to be numbered from 0 to 15 and index 16 looks beyond the end of the `v2v` array in `Mesh::RemoveUnusedVertices`.
There are at least three possible fixes:
1) Require meshes to use contiguous node numbers.
2) Modify `Mesh::RemoveUnusedVertices`, and possibly other methods, to search for the highest node index rather than assume it's going to be `Mesh:GetNV()-1`.
3) Modify the mesh file so that the number of vertices is larger than the highest index appearing in the file.
In this PR I chose option 3 because it is the …
> Quick fix of periodic mesh example [per-mesh-dev]

- README.md
- src/examples.md
Simplified filtering of examples/miniapps in the JavaScript at the end of `examples.md`.
Also tried to change the feature lists (radio buttons) to combo boxes, which seem cleaner now that the number of options is large.
Based on the `navier-miniapp` branch.
> Improved example filtering

- src/lininteg.md
Any opinions on how to represent correctly the Continuous Operator for the cases of 
`DomainLFGradIntegrator, VectorFEDomainLFCurlIntegrator, VectorFEDomainLFDivIntegrator` ? 
As is now the boundary contribution is omitted, as other BilinearFormIntegrators of similar nature (like WeakGrad, WeakDiv and WeakCurl integrators)
> adding new LF

- src/bilininteg.md
The `CurlCurlIntegrator` supports `MatrixCoefficient`. It is used in that way, for example, in ex25. This was added in https://github.com/mfem/mfem/commit/4d737d0358f2c6b07b16152b45294f00e57dd96f.
> CurlCurlIntegrator minor fix in description

- src/bilininteg.md
Changes:
Note: Wait with merge until https://github.com/mfem/mfem/pull/1655 has been approved.
> Improving description of coefficient types

- src/news.md
In preparation for the new redesign/overhaul of computing.llnl.gov, I unpublished all news on _that_ website dated before 1/1/19 (Comp web team is only keeping 2 years' worth of news). That action resulted in two broken news links on _this_ website. I unlinked those and, while I had news.md open, checked/updated all the other *.llnl.gov links.
> Link updates to news.md

- src/news.md
Subsequent to PR #86 in which I unlinked two articles that were unpublished from the Computing website, I have added back in new links to PDF versions of these articles, which are now hosted on computing.llnl.gov. Thus the accessibility of historical MFEM news remains intact.
> Link updates to news.md, part 2

- src/lininterp.md
This is a companion PR to PR [#1931](https://github.com/mfem/mfem/pull/1931).  It simply adds two lines to mention new support for curl and cross product operators in 2D.
> Adding curl and cross product interpolators suitable for use in 2D [test-lin-interp-dev]

- src/index.md
- src/news.md
My link crawler on computing.llnl.gov caught something that inspired me to check MFEM news links. So I ran a link checker on https://mfem.org/news/ and found several broken links, two from Computing (the file path for downloadable PDFs changed when the new site launched in March). 
Mar 18, 2021 - added new postdoc job opening (also added to index.md)
Oct 16, 2017 - unlinked old job posting
May 8, 2017 - updated Computing file path
Sep 19, 2016 - person no longer at MIT; linked to their GitHub profile instead
May 6, 2016 - linked to main Homebrew repo
Jan 6, 2016 -  updated Computing file path
> Fixed broken links in news

- src/fluids.md
I noticed some mathematical inconsistencies in the documentation and made a suggestion. Specifically, the terms relying on the solutions from previous steps are denoted with index n (rather than n+1) to indicate which terms are explicitly available. My solution may be different than what was intended, so please check.
> Minor fixes in fluids.md

- src/seminar.md
- src/videos.md
- Added Dr. Scovazzi video to `videos.md` including a new H2 heading
- Added YouTube playlist link to `seminar.md` plus a link over to `videos.md`
- Replaced placeholder link in green "Talk Recording" button on `seminar.md`
His abstract now appears in two places (`seminar.md` & `videos.md`). Redundancy OK? 
Page will look a little lopsided until the 2nd video is posted.
> Updated videos page with 1st seminar video

- src/seminar.md
- src/videos.md
1. Added new new "Conferences in 2022" heading to videos page; I placed this after the seminar series because the latter spans 2021-22
2. Added Camier GTC video link/abstract to videos page under new heading
3. Added Zanella and Isaac links/abstracts to videos page
4. Made title heading levels consistent among seminar videos (4 # instead of 5)
5. Updated Isaac link on seminar page
> Updated videos & seminar pages

- src/seminar.md
- src/videos.md
Updated seminar title and video link on `seminar.md`. Added seminar info, abstract, and embedded YT player to `videos.md`. Also moved the `<div>` to keep FEM videos in two neat columns.
> Add Fischer seminar video

- src/mesh-format-v1.x.md
- src/mesh-formats.md
This PR is meant to address the issue https://github.com/mfem/mfem/issues/3094.
> Fix some incorrect statements in the mesh format description

- src/tutorial/index.md
Mermaid upgraded from 9.1.7 to 9.2.0 which broke the tutorial diagram rendering. This should fix it.
> Fix mermaid diagram rendering

- src/bilininteg.md
- src/gpu-support.md
- src/howto/assembly_levels.md
Addresses this TODO item:
- Add a table for GPU coverage of bilinear/linear forms (Add a link to [this page](https://mfem.org/howto/assembly_levels/) from [GPU support](https://mfem.org/gpu-support/) and [BilinInteg](https://mfem.org/bilininteg/))
> Highlight the GPU support table

- src/videos.md
This adds @vladotomov seminar video to the "Conferences in 2022" section of `videos.md`. I linked TAMUCC to the university's home page; should it point somewhere more specific (e.g., a department)?
> Tomov video

- src/about.md
> A small fix in the bib item on the 'about' page

- src/bilininteg.md
`GradientIntegrator` (mixed operator in https://mfem.org/bilininteg/#vector-field-operators) range space should include `L^2(d)`
> `GradientIntegrator` range space

- src/seminar.md
- src/videos.md
- Added video links to the seminar page
- Added speaker info, thumbnails, and abstracts to the videos page
- Moved seminar section above 2023 workshop section on videos page
> Add Chan & Young seminar videos

- src/fem_bc.md
Small fixes stemming from issue [#4193](https://github.com/mfem/mfem/issues/4193)
> Correcting appearance of normal vector in Robin BCs for ND and RT fields

- src/index.md
- src/news.md
- src/tutorial/index.md
The AWS blog link on the tutorial page (line 8) still points to the 2023 blog post. A 2024 post is coming soon.
> Add news item for August tutorial

- src/tutorial/index.md
- src/workshop.md
1. Workshop: Event date and format were styled as `####`. I changed to `<h4>` so they wouldn't appear in the right-hand menu.
2. Tutorial: "Visualizations" had a weird indent not present on any other page. I removed `&nbsp;` from the headings on the page to fix alignment in the right-hand menu.
> Fixed two menu issues

- src/bilininteg.md
- src/examples.md
- src/lininteg.md
Hi Tzanio,
I think commit 41878ad won't be controversial as it simple aligns the notation with what you already wrote for the H(div) continuous boundary operators in the Bilinear Form Integrators page.
~Commit 9680418 might be. But, unless you are compensating for the sign within `VectorFEBoundaryTangentLFIntegrator`, which doesn't sound like something you would do(?), I think we do need to flip the sign in the docs?~
EDIT: We aren't compensating for the sign within `VectorFEBoundaryTangentLFIntegrator` (which I think is a good thing 🙂), so we definitely need the sign flip in the docs. I think the confusion might've arisen because it looks like the units tests we have for `VectorFEBoundaryTangentLFIntegrator` are all projections, where the domain and boundary operators appear both on the …
> Improve the notation for boundary integrators/operators

- src/fem_bc.md
In the description of boundary conditions for DG spaces, the following changes are made:
- a typo corrected
- noting that one needs to use `BoundaryMassIntegrator` instead of `MassIntegrator` for Robin conditions, per example 27
> Note BoundaryMassIntegrator for DG Robin BCs

- src/videos.md
**Content organization**
- Moved monthly seminars to the top
- Grouped all conferences videos with newest first
- Grouped all years of workshops videos with newest first
- Kept "Other Videos" at the bottom; they are not seminars, talks, conferences, etc.
**Headings**
- Retained year-specific headings for high-volume workshops but not for the relatively few conference videos
- Renamed multiple "Conferences in 20XX" headings to "Conferences & Talks" as a single heading
**Specific videos**
- Added February 2025 SIAM-SC video
- Added blurb for ExCALIBUR SLE video or else it would not display the horizonal rule separating it from the video beneath
> Overhaul of videos organization & one new video
